//NextJS Global Imports
import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

//Page: Component imports
import { Box } from '@chakra-ui/react'

//App: Component Imports
import { Auth } from 'components/Auth'
import { Navbar } from 'components/Navbar'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Personal Chef</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box as="main" pb={8}>

      </Box>
    </>
  )
} 