import Head from "next/head";
import dynamic from "next/dynamic";
import { Box, Container } from "@chakra-ui/react";
import Navbar from "components/navbar";

const Main = ({ children, router }) => {
  return (
    <Box as="main" pb={8}>
      <Head>
        <title>Personal Chef - Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      
      <Navbar path={router.asPath}/>

      <Container maxW="container.md" pt={14}>
        {children}
      </Container>
    </Box>
  );
};


export default Main